metadata:
  name: gemini-1.5-pro-srt-labeler
  provider: chat_google_genai
model_customizations:
  max_output_tokens: 16000
  model: models/gemini-1.5-pro-latest
  n: 1
  safety_settings:
    HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_NONE
    HARM_CATEGORY_HARASSMENT: BLOCK_NONE
    HARM_CATEGORY_HATE_SPEECH: BLOCK_NONE
    HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_NONE
  temperature: 0.0
  top_k: null
