backend_options:
  auto_create_first_user: srt-labeler
  title_generation:
    provider: openrouter
plugins:
  enabled:
    # - provider_chat_fireworks
    - provider_chat_google_genai
    - provider_openrouter
