backend_options:
  auto_create_first_user: srt-labeler
  title_generation:
    provider: openrouter
model:
  default_preset: llama-3.3-srt-labeler
plugins:
  enabled:
    - provider_chat_fireworks
    - provider_chat_google_genai
    - provider_openrouter
